name: themes
description: A new Flutter package project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.25.0
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
