name: analysis_logger
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  authenticator:
    path: ../authenticator
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
