name: configurator
description: |
  Provides a wrapper class for the FlutterFire RemoteConfig package to simplify its usage.
version: 1.0.0
publish_to: "none"

false_secrets:
  - example/**

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  meta: ^1.12.0

dev_dependencies:
  altive_lints: ^2.0.0-dev.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
