name: configurator
description: |
  Provides a wrapper class for the FlutterFire RemoteConfig package to simplify its usage.
version: 1.0.0
publish_to: "none"

false_secrets:
  - example/**

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  firebase_remote_config: ^6.1.0
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  altive_lints: ^1.25.0
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
