name: authenticator
description: Authenticator.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.16.0
  firebase_auth: ^4.6.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0
  riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  altive_lints: ^1.7.0
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.0.0

flutter:
