name: notification_sender
description: A new Flutter package project.
publish_to: "none"
version: 1.0.0
homepage: https://github.com/altive/flutter_app_template/tree/main/packages/notification_sender

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+1
  riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  timezone: ^0.9.0

dev_dependencies:
  altive_lints: ^1.7.0
  build_runner: ^2.2.1
  flutter_local_notifications_platform_interface: ^7.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.1
  plugin_platform_interface: ^2.1.3
  riverpod_generator: ^2.0.0

flutter:
