name: util
description: >
  This package stores general-purpose functions that are too small to be cut out into a stand-alone package.
publish_to: "none"
version: 1.0.0
homepage: https://github.com/altive/flutter_app_template/tree/main/packages/util

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  shared_preferences: ^2.0.15

dev_dependencies:
  altive_lints: ^1.14.1
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
