name: util
description: >
  This package stores general-purpose functions that are too small to be cut out into a stand-alone package.
publish_to: "none"
version: 1.0.0
homepage: https://github.com/altive/flutter_app_template/tree/main/packages/util

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.15

dev_dependencies:
  altive_lints: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
