name: util
description: >
  This package stores general-purpose functions that are too small to be cut out into a stand-alone package.
publish_to: "none"
version: 1.0.0
homepage: https://github.com/altive/flutter_app_template/tree/main/packages/util

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  altive_lints: ^2.0.0
  flutter_test:
    sdk: flutter
