name: ranking_note_app
description: Flutter App Template is a project that introduces an approach to architecture and project structure for developing Flutter apps.
publish_to: "none"
version: 1.0.0+10

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  altive_flutter_kit:
    git:
      url: https://github.com/altive/altive_flutter_kit.git
      version: ^1.1.1
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.1.5
  firebase_core: ^1.9.0
  firebase_crashlytics: ^2.2.5
  firebase_dynamic_links: ^3.0.0
  firebase_messaging: ^11.0.0
  firebase_performance: ^0.7.1+3
  firebase_remote_config: ^0.11.0+2
  firebase_storage: ^10.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^1.1.0
  gap: ^2.0.0
  google_sign_in: ^5.1.0
  hooks_riverpod: ^1.0.0-dev.7
  image_picker: ^0.8.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  linked_scroll_controller: ^0.2.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.0.5
  routemaster: ^0.9.5
  shared_preferences: ^2.0.8
  sign_in_with_apple: ^3.2.0
  sort_key_generator: ^0.2.0+1
  textfield_tags: ^1.4.2
  tuple: ^2.0.0
  uuid: ^3.0.4
  version: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: ^4.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.0.1

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  assets:
    style: dot-delimiter

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
