name: remote_parameter_fetcher
description: Fetch parameters set remotely.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  firebase_remote_config: ^4.2.1
  flutter:
    sdk: flutter
  meta: ^1.7.0
  riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.7.0
  build_runner: ^2.2.0
  mockito: ^5.3.0
  riverpod_generator: ^2.0.0
  test:
