name: pub_dev_api_client
description: Pub.dev API client package
version: 1.0.0

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  mock_web_server: ^5.0.0-nullsafety.1
  retrofit: ^4.6.0

dev_dependencies:
  altive_lints: ^2.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.5
  retrofit_generator: ^10.2.0
  test: ^1.28.0
