name: flutter_app
description: |
  The Flutter App Template is a starter kit for developing Flutter apps.
  It is also a project that Altive Inc continues to update as a sample of architecture, configuration, and package usage.
publish_to: "none"
version: 1.0.0+32

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  authenticator:
    path: ../core/authenticator
  awaitable_button: ^1.3.0
  cached_network_image: ^3.4.0
  clock: ^1.1.1
  cloud_firestore: ^6.0.3
  collection: ^1.18.0
  configurator:
    path: ../core/configurator
  connectivity_plus: ^6.1.5
  convenient_widgets: ^1.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  firebase_core: ^4.2.0
  firebase_performance: ^0.11.1+1
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  hooks_riverpod: ^3.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  linked_scroll_controller: ^0.2.0
  messenger:
    path: ../core/messenger
  package_info_plus: ^8.3.1
  pub_dev_api_client: ^1.0.0
  shared_preferences: ^2.5.3
  simple_logger: ^1.9.0+1
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  sort_key_generator: ^0.2.1
  themes: ^1.0.0
  tracker:
    path: ../core/tracker
  tuple: ^2.0.0
  url_launcher: ^6.3.2
  utils:
    path: ../core/utils
  uuid: ^4.5.1
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.2
  json_serializable: ^6.11.2
  mockito: ^5.6.1
  mocktail: ^1.0.4
  slang_build_runner: ^4.11.0

flutter_gen:
  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/sample_images/
