name: flutter_app
description: |
  The Flutter App Template is a starter kit for developing Flutter apps.
  It is also a project that Altive Inc continues to update as a sample of architecture, configuration, and package usage.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  analysis_logger:
    path: ../analysis_logger
  authenticator:
    path: ../authenticator
  awaitable_button: ^1.2.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.7.1
  collection: ^1.16.0
  convenient_widgets:
    path: ../convenient_widgets
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.0
  firebase_core: ^2.13.0
  firebase_dynamic_links: ^5.3.1
  firebase_performance: ^0.9.2+1
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  gap: ^2.0.0
  go_router: ^7.0.0
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.5
  intl: ^0.18.1
  json_annotation: ^4.8.0
  linked_scroll_controller: ^0.2.0
  modal_bottom_sheet: ^2.1.2
  package_info_plus: ^3.0.2
  rest_api_client:
    path: ../rest_api_client
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.0
  simple_logger: ^1.9.0+1
  sort_key_generator: ^0.2.0+1
  themes:
    path: ../themes/
  tuple: ^2.0.0
  url_launcher: ^6.1.10
  uuid: ^3.0.4
  version: ^3.0.2

dev_dependencies:
  altive_lints: ^1.7.0
  build_runner: ^2.3.3
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  go_router_builder: ^2.0.1
  json_serializable: ^6.6.1
  mockito: ^5.2.0
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.2

dependency_overrides:
  # Because flutter_app depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
  # So, because flutter_app depends on intl ^0.18.1, version solving failed.
  intl: 0.18.1

flutter_gen:
  enabled: true
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    outputs:
      style: dot-delimiter

flutter_icons:
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/sample_images/
