name: widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  convenient_widgets: ^1.0.0
  flutter:
    sdk: flutter
  themes: ^1.0.0
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  altive_lints: ^1.22.1
  build_runner: ^2.7.0
  custom_lint: ^0.8.0
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
