name: widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.3

resolution: workspace

dependencies:
  convenient_widgets: ^1.0.0
  flutter:
    sdk: flutter
  themes: ^1.0.0
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  altive_lints: ^2.0.0
  build_runner: ^2.4.13
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
