name: widget_catalog
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  convenient_widgets: ^1.0.0
  flutter:
    sdk: flutter
  themes: ^1.0.0
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  altive_lints: ^1.25.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  widgetbook_generator: ^4.0.0-alpha.4

flutter:
  uses-material-design: true
