name: messenger
description: |
  Provides a wrapper class for FlutterFire messaging and in_app_messaging packages to simplify its usage.
version: 1.0.0
homepage: https://altive.dev
publish_to: "none"

false_secrets:
  - example/**

environment:
  sdk: ^3.10.7

resolution: workspace

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  firebase_in_app_messaging: ^0.9.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  utils:
    path: ../utils

dev_dependencies:
  altive_lints: ^2.1.0
  firebase_core: ^4.2.0
  firebase_core_platform_interface: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
